### ISSUE TITLE
Panic while training

### ISSUE THREAD

**Issue by dolanor** [owulveryck/min-char-rnn#1]
After a while training, I got a panic. So here is the output log and I'm joining the .bin file that causes that.
[shakespeare.bin.gz](https://github.com/owulveryck/min-char-rnn/files/1480172/shakespeare.bin.gz)

```
$ echo "starting sequence for the sampling" | ./min-char-rnn -restore shakespeare.bin -train 
2017/11/16 20:43:54 [100] {NaN}
2017/11/16 20:43:54 [200] {NaN}
2017/11/16 20:43:55 [300] {NaN}
2017/11/16 20:43:55 [400] {NaN}
2017/11/16 20:43:56 [500] {NaN}
2017/11/16 20:43:56 [600] {NaN}
2017/11/16 20:43:57 [700] {NaN}
2017/11/16 20:43:57 [800] {NaN}
2017/11/16 20:43:58 [900] {NaN}
2017/11/16 20:43:58 [1000] {NaN}
panic: runtime error: index out of range

goroutine 1 [running]:
gonum.org/v1/gonum/stat/distuv.Categorical.Rand(0xc4201918c0, 0x41, 0x41, 0xc420191b00, 0x41, 0x41, 0xc420487988, 0xc420191b00)
	/home/dolanor/go/src/gonum.org/v1/gonum/stat/distuv/categorical.go:124 +0x129
github.com/owulveryck/min-char-rnn/codec/char.(*Char).ApplyDist(0xc420081290, 0xc420191440, 0x41, 0x41, 0xc420191440, 0x41, 0x41)
	/home/dolanor/go/src/github.com/owulveryck/min-char-rnn/codec/char/char.go:211 +0x2ba
github.com/owulveryck/min-char-rnn/codec.(Codec).ApplyDist-fm(0xc420191440, 0x41, 0x41, 0xfff8000000000000, 0xc420191440, 0x41)
	/home/dolanor/go/src/github.com/owulveryck/min-char-rnn/main.go:107 +0x4d
github.com/owulveryck/min-char-rnn/rnn.(*RNN).Predict(0xc42009e388, 0xc420170000, 0x23, 0x40, 0x1f4, 0xc420487d78, 0x19, 0x19, 0x922530)
	/home/dolanor/go/src/github.com/owulveryck/min-char-rnn/rnn/rnn.go:329 +0x460
main.main()
	/home/dolanor/go/src/github.com/owulveryck/min-char-rnn/main.go:107 +0x751
```

**Comment by owulveryck** [comment]
I will have a look. 
I don't check the size of the neurons and the matrices, so it may be a consequence of different environment variables between the initial training and the "retraining" (with restore).
Can you provide the environment variables as well please ?

**Comment by dolanor** [comment]
Sorry I took so much time to answer.
It was the same settings as for the shakespeare training.
